services:
  car-insurance-sales-bot:
    image: car-insurance-sales-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TelegramBotToken
      - Mindee__ApiKey
      - Mistral__ApiKey
